name: Routine

on:
  schedule:
    - cron: '0 10 * * * '

jobs:
  routine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install

      - name: Mark them as done
        env:
          ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
        run: yarn routine 1152701043959235

      - name: Live long and prosper
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "devops - auto keepalive before 60 days of inactivity"
          committer_email: "runzhou.li@gmail.com"
